name: Deploys to Prod

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
      DROPLET_PASSWORD:
        required: true
      RECAPTCHA_SECRET:
        required: true
      JWT_SECRET:
        required: true
      POSTGRES_PASSWORD:
        required: true
  
  workflow_dispatch:

env:
  BASE_PATH: ${{ vars.BASE_PATH }}
  ENVIRONMENT: "remote"
  RECAPTCHA_SECRET: ${{ secrets.RECAPTCHA_SECRET }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  DROPLET_IP: ${{ vars.DROPLET_IP }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  SQLX_OFFLINE: true

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Copy compose.yml to droplet
        run: sshpass -v -p ${{ secrets.DROPLET_PASSWORD }} scp -o StrictHostKeyChecking=no compose.yml  root@${{ vars.DROPLET_IP }}:~
      
      - name: Copy proxy/templates to droplet
        run: sshpass -v -p ${{ secrets.DROPLET_PASSWORD }} scp -r -o StrictHostKeyChecking=no proxy root@${{ vars.DROPLET_IP }}:~

      - name: Deploy and run Docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.DROPLET_IP }}
          envs: BASE_PATH, ENVIRONMENT, RECAPTCHA_SECRET, JWT_SECRET, DROPLET_IP, POSTGRES_PASSWORD

          username: root
          password: ${{ secrets.DROPLET_PASSWORD }}
          script: |
            cd ~
            docker compose down
            docker compose pull
            docker compose up -d
  
  # api-tests:
  #   name: Test APIs
  #   needs: deployment
  #   uses: ./.github/workflows/integration-tests.yml
  
  # e2e-tests:
  #   name: End to end tests
  #   needs: deployment
  #   uses: ./.github/workflows/e2e.yml

